export enum ServiceType {
  HAIRCUT = 'HAIRCUT',
  HAIR_COLORING = 'HAIR_COLORING',
  HAIR_STYLING = 'HAIR_STYLING',
  HAIR_TREATMENT = 'HAIR_TREATMENT',
  NAIL = 'NAIL',
  SKIN_CARE = 'SKIN_CARE',
  MAKE_UP = 'MAKE_UP',
  OTHERS = 'OTHERS'
}